/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	floatingipproviderv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/floatingipprovider/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFloatingIPProviders implements FloatingIPProviderInterface
type FakeFloatingIPProviders struct {
	Fake *FakeK8sV1
}

var floatingipprovidersResource = schema.GroupVersionResource{Group: "k8s.ovn.org", Version: "v1", Resource: "floatingipproviders"}

var floatingipprovidersKind = schema.GroupVersionKind{Group: "k8s.ovn.org", Version: "v1", Kind: "FloatingIPProvider"}

// Get takes name of the floatingIPProvider, and returns the corresponding floatingIPProvider object, and an error if there is any.
func (c *FakeFloatingIPProviders) Get(ctx context.Context, name string, options v1.GetOptions) (result *floatingipproviderv1.FloatingIPProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(floatingipprovidersResource, name), &floatingipproviderv1.FloatingIPProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*floatingipproviderv1.FloatingIPProvider), err
}

// List takes label and field selectors, and returns the list of FloatingIPProviders that match those selectors.
func (c *FakeFloatingIPProviders) List(ctx context.Context, opts v1.ListOptions) (result *floatingipproviderv1.FloatingIPProviderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(floatingipprovidersResource, floatingipprovidersKind, opts), &floatingipproviderv1.FloatingIPProviderList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &floatingipproviderv1.FloatingIPProviderList{ListMeta: obj.(*floatingipproviderv1.FloatingIPProviderList).ListMeta}
	for _, item := range obj.(*floatingipproviderv1.FloatingIPProviderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested floatingIPProviders.
func (c *FakeFloatingIPProviders) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(floatingipprovidersResource, opts))
}

// Create takes the representation of a floatingIPProvider and creates it.  Returns the server's representation of the floatingIPProvider, and an error, if there is any.
func (c *FakeFloatingIPProviders) Create(ctx context.Context, floatingIPProvider *floatingipproviderv1.FloatingIPProvider, opts v1.CreateOptions) (result *floatingipproviderv1.FloatingIPProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(floatingipprovidersResource, floatingIPProvider), &floatingipproviderv1.FloatingIPProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*floatingipproviderv1.FloatingIPProvider), err
}

// Update takes the representation of a floatingIPProvider and updates it. Returns the server's representation of the floatingIPProvider, and an error, if there is any.
func (c *FakeFloatingIPProviders) Update(ctx context.Context, floatingIPProvider *floatingipproviderv1.FloatingIPProvider, opts v1.UpdateOptions) (result *floatingipproviderv1.FloatingIPProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(floatingipprovidersResource, floatingIPProvider), &floatingipproviderv1.FloatingIPProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*floatingipproviderv1.FloatingIPProvider), err
}

// Delete takes name of the floatingIPProvider and deletes it. Returns an error if one occurs.
func (c *FakeFloatingIPProviders) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(floatingipprovidersResource, name), &floatingipproviderv1.FloatingIPProvider{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFloatingIPProviders) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(floatingipprovidersResource, listOpts)

	_, err := c.Fake.Invokes(action, &floatingipproviderv1.FloatingIPProviderList{})
	return err
}

// Patch applies the patch and returns the patched floatingIPProvider.
func (c *FakeFloatingIPProviders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *floatingipproviderv1.FloatingIPProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(floatingipprovidersResource, name, pt, data, subresources...), &floatingipproviderv1.FloatingIPProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*floatingipproviderv1.FloatingIPProvider), err
}
