/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/floatingipprovider/v1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/floatingipprovider/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FloatingIPProvidersGetter has a method to return a FloatingIPProviderInterface.
// A group's client should implement this interface.
type FloatingIPProvidersGetter interface {
	FloatingIPProviders() FloatingIPProviderInterface
}

// FloatingIPProviderInterface has methods to work with FloatingIPProvider resources.
type FloatingIPProviderInterface interface {
	Create(ctx context.Context, floatingIPProvider *v1.FloatingIPProvider, opts metav1.CreateOptions) (*v1.FloatingIPProvider, error)
	Update(ctx context.Context, floatingIPProvider *v1.FloatingIPProvider, opts metav1.UpdateOptions) (*v1.FloatingIPProvider, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.FloatingIPProvider, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.FloatingIPProviderList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.FloatingIPProvider, err error)
	FloatingIPProviderExpansion
}

// floatingIPProviders implements FloatingIPProviderInterface
type floatingIPProviders struct {
	client rest.Interface
}

// newFloatingIPProviders returns a FloatingIPProviders
func newFloatingIPProviders(c *K8sV1Client) *floatingIPProviders {
	return &floatingIPProviders{
		client: c.RESTClient(),
	}
}

// Get takes name of the floatingIPProvider, and returns the corresponding floatingIPProvider object, and an error if there is any.
func (c *floatingIPProviders) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.FloatingIPProvider, err error) {
	result = &v1.FloatingIPProvider{}
	err = c.client.Get().
		Resource("floatingipproviders").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FloatingIPProviders that match those selectors.
func (c *floatingIPProviders) List(ctx context.Context, opts metav1.ListOptions) (result *v1.FloatingIPProviderList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.FloatingIPProviderList{}
	err = c.client.Get().
		Resource("floatingipproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested floatingIPProviders.
func (c *floatingIPProviders) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("floatingipproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a floatingIPProvider and creates it.  Returns the server's representation of the floatingIPProvider, and an error, if there is any.
func (c *floatingIPProviders) Create(ctx context.Context, floatingIPProvider *v1.FloatingIPProvider, opts metav1.CreateOptions) (result *v1.FloatingIPProvider, err error) {
	result = &v1.FloatingIPProvider{}
	err = c.client.Post().
		Resource("floatingipproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(floatingIPProvider).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a floatingIPProvider and updates it. Returns the server's representation of the floatingIPProvider, and an error, if there is any.
func (c *floatingIPProviders) Update(ctx context.Context, floatingIPProvider *v1.FloatingIPProvider, opts metav1.UpdateOptions) (result *v1.FloatingIPProvider, err error) {
	result = &v1.FloatingIPProvider{}
	err = c.client.Put().
		Resource("floatingipproviders").
		Name(floatingIPProvider.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(floatingIPProvider).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the floatingIPProvider and deletes it. Returns an error if one occurs.
func (c *floatingIPProviders) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("floatingipproviders").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *floatingIPProviders) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("floatingipproviders").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched floatingIPProvider.
func (c *floatingIPProviders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.FloatingIPProvider, err error) {
	result = &v1.FloatingIPProvider{}
	err = c.client.Patch(pt).
		Resource("floatingipproviders").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
