/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/floatingipclaim/v1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/floatingipclaim/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FloatingIPClaimsGetter has a method to return a FloatingIPClaimInterface.
// A group's client should implement this interface.
type FloatingIPClaimsGetter interface {
	FloatingIPClaims() FloatingIPClaimInterface
}

// FloatingIPClaimInterface has methods to work with FloatingIPClaim resources.
type FloatingIPClaimInterface interface {
	Create(ctx context.Context, floatingIPClaim *v1.FloatingIPClaim, opts metav1.CreateOptions) (*v1.FloatingIPClaim, error)
	Update(ctx context.Context, floatingIPClaim *v1.FloatingIPClaim, opts metav1.UpdateOptions) (*v1.FloatingIPClaim, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.FloatingIPClaim, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.FloatingIPClaimList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.FloatingIPClaim, err error)
	FloatingIPClaimExpansion
}

// floatingIPClaims implements FloatingIPClaimInterface
type floatingIPClaims struct {
	client rest.Interface
}

// newFloatingIPClaims returns a FloatingIPClaims
func newFloatingIPClaims(c *K8sV1Client) *floatingIPClaims {
	return &floatingIPClaims{
		client: c.RESTClient(),
	}
}

// Get takes name of the floatingIPClaim, and returns the corresponding floatingIPClaim object, and an error if there is any.
func (c *floatingIPClaims) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.FloatingIPClaim, err error) {
	result = &v1.FloatingIPClaim{}
	err = c.client.Get().
		Resource("floatingipclaims").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FloatingIPClaims that match those selectors.
func (c *floatingIPClaims) List(ctx context.Context, opts metav1.ListOptions) (result *v1.FloatingIPClaimList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.FloatingIPClaimList{}
	err = c.client.Get().
		Resource("floatingipclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested floatingIPClaims.
func (c *floatingIPClaims) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("floatingipclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a floatingIPClaim and creates it.  Returns the server's representation of the floatingIPClaim, and an error, if there is any.
func (c *floatingIPClaims) Create(ctx context.Context, floatingIPClaim *v1.FloatingIPClaim, opts metav1.CreateOptions) (result *v1.FloatingIPClaim, err error) {
	result = &v1.FloatingIPClaim{}
	err = c.client.Post().
		Resource("floatingipclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(floatingIPClaim).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a floatingIPClaim and updates it. Returns the server's representation of the floatingIPClaim, and an error, if there is any.
func (c *floatingIPClaims) Update(ctx context.Context, floatingIPClaim *v1.FloatingIPClaim, opts metav1.UpdateOptions) (result *v1.FloatingIPClaim, err error) {
	result = &v1.FloatingIPClaim{}
	err = c.client.Put().
		Resource("floatingipclaims").
		Name(floatingIPClaim.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(floatingIPClaim).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the floatingIPClaim and deletes it. Returns an error if one occurs.
func (c *floatingIPClaims) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("floatingipclaims").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *floatingIPClaims) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("floatingipclaims").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched floatingIPClaim.
func (c *floatingIPClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.FloatingIPClaim, err error) {
	result = &v1.FloatingIPClaim{}
	err = c.client.Patch(pt).
		Resource("floatingipclaims").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
